### ISSUE TITLE
Cannot activate right-click function blocks without the chisel GUI opening

### ISSUE THREAD

**Issue by VictiniX888** [Chisel-2/Chisel-2#119]
https://gfycat.com/WhichArtisticAlabamamapturtle

Chisel version: Build 25
Forge version: 1277

**Comment by tterrag1098** [comment]
Half easy. I've changed the title to reflect what's left of this issue.

**Comment by tterrag1098** [comment]
GUIs work fine now though.

**Comment by VictiniX888** [comment]
How about Buttons and Levers (and stuff like that)?

**Comment by tterrag1098** [comment]
I can either hack in an ugly fix, or wait and try and fix this with a forge PR (who knows how long that could take). Forge issue report at MinecraftForge/MinecraftForge#1631

Curious what @TheCricket and @Drullkus and @CptSpaceToaster think.

**Comment by CptSpaceToaster** [comment]
Forge PR sounds like the way to go here.  If Right clicking blocks opens up the chisel gui, is only a minor inconvenience for players.  They can simply move their selected item to something that's not a chisel and keep on playing.

We can tell them that a fix is on the way eventually, and that we know the bug exists.

Because it's not destroying anything, there isn't a great need to rush an "ugly fix".

@TheCricket and @Drullkus, Thoughts?

**Comment by Drullkus** [comment]
I agree with Toaster

There's no need to rush for a fix unless Lex isn't feeling fLEXable about accepting the PR

I regret nothing

**Comment by CptSpaceToaster** [comment]
Best pun. 10/10

**Comment by hron84** [comment]
Could we temporary need sneak+right click to activate chisel gui, and keep normal right-click action intact? Or, it could be configurable... I think sneak+right click is not too uncomfy (very common in other mods) and lets players use their items freely.

**Comment by tterrag1098** [comment]
Why was this closed?

**Comment by TheCricket** [comment]
because it works fine now :)

**Comment by hron84** [comment]
Yep, confirmed, it works good now.
