### ISSUE TITLE
Fake grass-block suggestion

### ISSUE THREAD

**Issue by MeshPL** [Chisel-2/Chisel-2#264]
Etho (a youtuber) complains a lot about not being able to use grass in the desert, because of how bad it looks there. This made me come up with this idea: fake grass. Crafted with grass block (that one requiring silktouch) and some kind of dy

**Comment by MeshPL** [comment]
(Writing on a mobile phone, accidentaly pressed Submit)

e, fake grass would solve such problems. Using chisel would make you able to select colour of grass, including both colours found naturally (bluish grass in cold biomes etc.) as well as some fake colours (lime, red, purple). Fake grass would not spread nor be able to die.

**Comment by CptSpaceToaster** [comment]
I'd assume you can't plant anything on fake grass?

**Comment by MeshPL** [comment]
It contains dirt, then why not? The main feature is colour independant from the biome. However being able to plant plants on such a block, would help you create, by example, cool looking oasis in the middle of desert, with both green grass and flowers. Maybe tall fake grass would be useful as well.

**Comment by warlordjones** [comment]
I quite like the idea, but not sure it quite fits with the theme of the mod.

**Comment by CptSpaceToaster** [comment]
Yeah... the biggest concern I have, is that it functions as normal grass.... I'm not against it either, it just seems a little weird to chisel grass into a color that won't change.

From my perspective, it fits into the same theme of the mod, as it's just changing a block to provide the same funciton, but look a bit different in the process... I just think we should be careful with feature creep. , and what all we add in.

@TheCricket What do you think?  This is your decision.

**Comment by Drullkus** [comment]
We could add a recipe for throwing seeds and green dye with dirt instead of chiseling it. Idk :P

**Comment by Oxosorrel** [comment]
What your looking for is artificial turf. http://en.m.wikipedia.org/wiki/Artificial_turf which is basically grass carpet. It's what we should use instead of grass in desert towns in real life anyway. If you say its artificial turf, no one will expect to plant in it, and it sticks with the theme of just blocks. 
So use 3 green carpet over over 6 pressure plates 6 or 6 planks to make the block of turf. Chisel it to different colors or "mow" patterns. Then build sweet putt putt golf courses, lay road lines ontop and make soccer stadiums, use it outside of a 9x9 trailer park for landscapes... And tame some wolves and make dog runs!

**Comment by CptSpaceToaster** [comment]
+1 for the artificial turf

**Comment by warlordjones** [comment]
I had a mod to do this, I can't remember if its updated to latest, but I'll update it if there is interest. I'd say its out of scope for chisel.

**Comment by warlordjones** [comment]
I feel like we don't need this open because we also have #316
