### ISSUE TITLE
Futura Controller texture

### ISSUE THREAD

**Issue by HanFox** [Chisel-2/Chisel-2#279]
I'm aware Futura is meant to be WIP, or at least they're still in a WIP folder with redundant Base/Overlay folders alongside, but are the Controller textures being re-thought?

Currently it's just a repetition of the "corners"/junctions, horizontal, vertical and central over and over and over....

Could it not just simply be controller.corner/junction.png, controller.horizontal.png, controller.vertical.png and controller.centre.png instead of the huge textures currently? The idea is to make a faux controller isn't it? It only has 2 animations (if I recall correctly the vertical one just gets rotated in-game to make horizontals) and the centre is actually static when active and changes between an A and B texture for each adjacent centre piece.

I'm just concerned it's being over-complicated (and thus textures being over-bloated), unless there's a bigger picture yet to be revealed.

**Comment by CptSpaceToaster** [comment]
so..... it can't be fixed with our small CTM renderer, as that works by dividing the block texture [4 segments](https://github.com/TheCricket/Chisel-2/blob/ctm_refactor2/src/main/java/com/cricketcraft/chisel/client/render/CTM.java#L10-L58)  The only other option was to use this massive texture set (much like optifine's CTM texture format) and... simply duplicate the entries.

This left us (probably the old developers actually) with the problem, that they wanted this block/behavior, but they couldn't repeat it in any way...  

So, this older format was used..... We probably could solve it by adding a slightly different render type, but... we're stuck in a refactor that needs to probably happen first before this can occur.

**Comment by HanFox** [comment]
Fair enough.

It's just simply the fact that this particular texture, in it's current form, is basically about 75% repetition and if in the slightest a particular renderer were done just to translate that (using your renderer info) e.g. 0, 1, 3, 4, 5, 7, 12, 13, 15 were all just one texture in a file called junction.png. So a special case renderer would definitely be a good idea in my opinion (for this and any other texture that isn't actually visually using the CTM function for joining) :)

For now, from my resourcepack perspective, I'll have to ignore that texture. To do it how I want it (to properly create a faux AE Controller) I'd have 2 or 3 (depending on exactly how each png is being used) HUGE (over 1MB / 2048px * 24576px files at 512x) pngs (and if the base/overlay idea is every implemented that's then 4 - 6 textures). Even at 64x they end up being pretty beasty and considering how MC eats resources at times especially in MC1.7 with HD packs...

**Comment by TheCricket** [comment]
Done
