### ISSUE TITLE
Render Bug with EnderIO

### ISSUE THREAD

**Issue by phillyfan666** [Chisel-2/Chisel-2#334]
Glowstone painted as waterstone with EnderIO Painting Machine let's you see through terrain. 
![2015-06-18_12 58 44](https://cloud.githubusercontent.com/assets/12955457/8237025/64a3bc20-15ba-11e5-9ae3-6cf76e988c19.png)
![2015-06-18_12 58 50](https://cloud.githubusercontent.com/assets/12955457/8237024/64a0102a-15ba-11e5-8553-530ff69ba1cb.png)

**Comment by CptSpaceToaster** [comment]
Only glowstone?  Or do other blocks do this as well?

**Comment by TheCricket** [comment]
Thats not a bug thats the actual texture

**Comment by TheCricket** [comment]
doesnt fix this my b

**Comment by utoc** [comment]
Hi there,

I'd like to add to this issue as we've also observed this in the BBQsauce pack.  The issue is that the render of waterstone/lavastone on top of a transparent block like glowstone can cause some very interesting effects.  I've attached a few images.  I can't tell from your FIX reference if you've actually fixed this issue or not.  If this should be reported to EnderIO instead, please let me know.

Connected textures with these blocks seems to follow a pattern.  Chisel variants and their painted glowstone counterparts all try to connect to each other.  Blocks on the LEFT (facing the block) of the Chisel 2 block turn into their element, water or lava.  Blocks on the right are missing the water or lava.  When the water or lava texture is missing, the block becomes transparent.

https://i.imgur.com/5NkSJvd.png

https://i.imgur.com/S1gGh0x.png

Additionally, you get some kind of extra texture/animation in the inventory screen and when holding the item.

https://i.imgur.com/2vljSKX.png

https://i.imgur.com/3LTN8Y7.png

We're running Chisel 2 v2.3.10.37, FML 1448.  A full modlist is located here: https://www.reddit.com/r/BBQSauce/wiki/modlist  We are running FastCraft.

**Comment by TheCricket** [comment]
this isnt a problem...

**Comment by CptSpaceToaster** [comment]
should the base block icon have anything there? a white pixel perhaps?  Or will that cause issue when we render multilayer?
