### ISSUE TITLE
Crash with ancient trees

### ISSUE THREAD

**Issue by Staegrin** [Chisel-2/Chisel-2#347]
Updated chisel to version 2.4.0 and crashed on startup

crashlog:
http://pastebin.com/F1aUb9rG
fml-client-latest:
https://gist.github.com/Staegrin/e08baad435821dfab01a

**Comment by ate0ate** [comment]
This is on ancient trees end and is due to chisel's api changes (creation). Scott is aware and stated that he would fix this as soon as the official chisel 2 api was released. For now disabling chisel 2 compatibility in the ancient trees config will prevent the crash, but you can't chisel ancient trees blocks.

check https://github.com/MinecraftModArchive/Dendrology/issues/31 for more info...
