### ISSUE TITLE
Wrong textures being assigned to some blocks. 

### ISSUE THREAD

**Issue by killerscorpion** [Chisel-2/Chisel-2#366]
Forge 1481 
Chisel 2.4.1.40
Fastcraft is enabled.

Some blocks are displaying the wrong texture, the picture below is showing the chisel gui for "marble pillar" blocks but are being overlapped with the "worn metal column" texture. I fixed the issue by deleting the config file and running the game again. But after some time the problem comes back.

Other blocks are displaying the same "worn metal column" texture, scrolling through NEI ive seen the following blocks with the same texture:
-Striped voidstone pillar
-striped energised voidstone pillar
-Plain packed ice pillar with plain capstone
-Plain packed ice pillar with greek capstone
-Greek packed ice pillar with plain capstone
-Greek packed ice pillar with greek capstone
-Purpled worn fantasy bricks in disarray
-Worn fantasy brick
-Worn fantasy bricks in disarray
-factory block/ vertical venting
-Large dirt bricks on top of dirt
-Vertical dirt
-Crumbling dirt
![2015-07-08_20 58 51](https://cloud.githubusercontent.com/assets/10732882/8587823/d5e374f0-25b6-11e5-8bf9-b60f3444c5d7.png)

**Comment by ferreusveritas** [comment]
Chisel 2 - 2.4.1.40
Forge 10.13.2.1291

I have the same problem..  I'm running with no other mods installed.
It appears that what all of these blocks have in common is that they are CTMV textures.
The other CTM textures are unaffected.  Since the CTM code has recently been aggressively rewritten I suspect some things may have fallen through the cracks.

When blocks are placed in the world they are rendered correctly.  When looking at the blocks in inventory they change depending on what block was placed last.  The texture on the block in the inventory can actually be partial CTMV textures,

Tterrag did a fine job cleaning up the CTM rendering code but this bug isn't obvious and has been around since Chisel  2.4.0.

**Comment by TheCricket** [comment]
This was a super render heavy update and we can't possibly check every single block in chisel

**Comment by tterrag1098** [comment]
override texture must be sticking around somehow. I will poke later.
