### ISSUE TITLE
See Through Hex Plating Block on Carpenter's Block 

### ISSUE THREAD

**Issue by jaxmacky** [Chisel-2/Chisel-2#382]
Chisel2-2.4.1.40
Forge 10.13.4.1448-1.7.10
Carpenter's Blocks v3.3.7 DEV - MC 1.7.10

Hex Plating Block becomes See Through when placed on Carpenter Block. Full Block on Left, Hex Plating  on Carpenters on right.

![2015-07-30_01 31 26](https://cloud.githubusercontent.com/assets/8409769/8977104/7cbd3a40-365b-11e5-9631-95c7e5956151.png)

**Comment by TheCricket** [comment]
What they do is use the function getIcon which is the black part, so their code is correct but not for our render system

**Comment by CptSpaceToaster** [comment]
What happens if we "fill in" the empty area with white pixels?  Does the multi-layer renderer draw over the white just fine?  Or does it start z-fighting?

to improve the situation a tiny bit... we could just fill in the block so it only looks like "color" is broken.

**Comment by TheCricket** [comment]
it z-fights a little from certain angles and distances

**Comment by Drullkus** [comment]
It's not wall-hacking in the picture above.

**Comment by CptSpaceToaster** [comment]
That's good then.

**Comment by MrCheeze96** [comment]
Without knowing anything about how the code works etc, I was just thinking that this might be a solution?

Wouldn't it be possible to override the getIcon function inside your class files? So that when someone makes the call for getIcon you have your own version of getIcon on the blocks that need it. For example Hex Plating, and inside this override function you can make the calls that are needed to render the block correctly.
