### ISSUE TITLE
Concrete allows for "moonwalking"

### ISSUE THREAD

**Issue by einsteinsci** [Chisel-2/Chisel-2#409]
Put concrete against a wall and walk against that wall (slightly) diagonally. Then turn to face the other way diagonally, still against the wall, while continuing to hold down W. You will now be walking the same direction as you were when you first hit the wall, but now it's somewhat backwards, and still holding the forward key. In other words, you're moonwalking.

I honestly have no idea how I discovered this. I'm guessing it has to do with the algorithm you use to accelerate the player, specifically when the player hits a wall.

This picture should illustrate the process to reproduce:
![2015-09-05_19 06 28](https://cloud.githubusercontent.com/assets/4753715/9702067/3dcc3f4c-5402-11e5-8ae9-cf84f3f73df5.png)

Tested with 2.5.0.40 (FTB Infinity) and 2.5.0.43 (alone with no other mods)

**Comment by Drullkus** [comment]
![https://pbs.twimg.com/media/BrnfdXpIMAAAyTn.jpg:large](https://pbs.twimg.com/media/BrnfdXpIMAAAyTn.jpg:large)

**Comment by TheCricket** [comment]
I dont see this as a problem at all

**Comment by Drullkus** [comment]
@TheCricket :)

**Comment by einsteinsci** [comment]
I'd probably consider this a feature as well.

**Comment by lamialily** [comment]
If you have the Hats mod, then I'm sure you know what you must do.

**Comment by ZeekDaGeek** [comment]
This doesn't sound like a problem when it's described as moonwalking, however, it's annoying bug that made me replace my whole floor in the past.

Imagine you have a vanilla door, you run towards it to go through and instead you bump into the door hinge and you attempt correct and go towards the opening, it's impossible, you keep running along the wall.

Instead in order to get through a doorway you have to walk at the door carefully crouching and hope you don't bump into anything and the whole process makes you look like a drunk.

You should never make the player feel like they've lost movement control, it's annoying.

**Comment by einsteinsci** [comment]
@ZeekDaGeek Considering that concrete has a 15/16 height (kinda like soul sand), going through a door would be impossible without another block to buffer (this is a feature in vanilla MC). The situation you have just described can never occur. Either there's a buffer of blocks in front of the door, which prevents moonwalking, or the player can't enter the door at all, because of the slightly lowered height of concrete.

**Comment by Drullkus** [comment]
What @einsteinsci just said. 

@TheCricket pls close and lock :)
